deutsch1 = {
    "@": "ет",
    "aber": "але, однак",
    "Abschied": "прощання",
    "ach so!": "Ось як! / Значить так!",
    "achten": "звертати увагу, цінувати, поважати",
    "ähnlich": "схожий, подібний",
    "allein": "самотній, один",
    "andere": "інший",
    "anders": "по-іншому, інший",
    "ankreuzen": "відмітити хрестиком",
    "antworten": "відповідати",
    "auch": "також, теж",
    "auf Wiederhören": "до зв'язку",
    "auf Wiedersehen!": "до побачення!",
    "auf": "на (горизонтальній поверхні)",
    "bald": "скоро",
    "Begrußung": "привітання (Hallo!, Guten Morgen, ...)",
    "benutzen": "використовувати, користуватися",
    "Beruf": "професія",
    "besetzen": "зайнятий, окупований",
    "bestellen": "замовляти",
    "Betonung": "наголос",
    "bezahlen": "платити, сплачувати",
    "bis später": "до зустрічі",
    "bitte ?": "вибачте ?",
    "brauchen": "потребувати, мати потребу",
    "da": "тут, ось",
    "dann": "тоді, потім",
    "das Alter": "вік",
    "das Auge / die Augen": "око / очі",
    "das Aussage": "ствердження, судження, свідотцтсво",
    "das Auto": "автомобіль",
    "das Bild": "малюнок, картина",
    "das Brot": "хліб",
    "das Dorf": "село",
    "das Ei": "яйце",
    "das Feuer / die Flamme": "вогонь",
    "das Fleisch": "м`ясо",
    "das Gebiet": "область, територія",
    "das Geld": "гроші",
    "das Gesicht": "обличчя",
    "das Gespräch, -e": "розмова",
    "das Getränk, -e": "напій",
    "das Gewürz, -e": "спеція, пряність",
    "das Gleiche": "те саме",
    "das Gramm": "грам",
    "das ist dasselbe wie": "Це те ж саме, що...",
    "das ist Ich": "це я",
    "das Jahr, -e": "рік",
    "das Kind, -er": "дитина",
    "das Lehrbuch": "підручник",
    "das Mädchen": "дівчинка, дівчина",
    "das Nomen": "іменник",
    "das Ohr / die Ohren": "вухо / вуха",
    "das Öl, -e": "олія",
    "das Orange": "апельсин",
    "das Passwort": "пароль",
    "das Programm": "програма",
    "das Semester": "семестер",
    "das Wasser": "вода",
    "das Wort": "слово",
    "der Abend, -e": "вечір",
    "der Apfel": "яблуко",
    "der Artz / die Ärtze": "лікар / лікарі",
    "der Bäckerei": "пекарня",
    "der Baum": "дерево",
    "der Becher": "стакан, чашка, бокал, кружка",
    "der Benutzer": "користувач",
    "der Bruder": "брат",
    "der Enkel": "онук",
    "der Fehler": "помилка",
    "der Finger": "палець на руці",
    "der Firma": "фірма",
    "der Fisch": "риба",
    "der Großvater": "дідусь",
    "der Haushalt": "домашнє господарство",
    "der Joghurt": "йогурт",
    "der Junge": "хлопчик",
    "der Käse": "сир, в тому числі творог",
    "der Knoblauch": "часник",
    "der Krieg": "війна",
    "der Kuchen": "пиріг, тістечко",
    "der Kunde / der Klient": "клієнт, покупець",
    "der Lehrer": "вчитель, викладач",
    "der Mais": "кукурудза",
    "der Monat, -e": "місяць",
    "der Neffe": "племінник",
    "der Opa": "дідусь",
    "der Pfannkuchen": "млинець",
    "der Pilz": "гриб",
    "der Rucksack": "рюкзак",
    "der Saft / die Säfte": "сік / соки",
    "der Sohn": "син",
    "der Stuhl / die Stühle": "стілець / стільці",
    "der Tag, -e": "день",
    "der Termin": "зустріч, термін",
    "der Tisch": "стіл",
    "der Ukraine": "Україна",
    "der Urlaub": "відпустка",
    "der Vater": "тато",
    "der Verkäufer": "продавець",
    "der Wagen": "візок, коляска, автомобіль",
    "der Witwer": "вдівець",
    "der Zwiebel": "цибуля, цибулина",
    "die Achtung": "увага, повага",
    "die Anfrage": "запит (request)",
    "die Anmeldung": "реєстрація, заявка, вхід в обліковий запис",
    "die Antwort, -en": "відповідь",
    "die Anzeige": "оголошення, заява",
    "die Arbeit": "праця, робота",
    "die Banane": "банан",
    "die Birne": "груша",
    "die Brille": "окуляри",
    "die Brötchen": "булочка",
    "die Dose": "консервна банка, коробочка",
    "die Eltern": "батьки",
    "die Enkelin": "онучка",
    "die Erdbeere": "полуниця",
    "die Familie, -en": "сім'я, родина",
    "die Ferien": "канікули, відпустка",
    "die Flasche": "пляшка",
    "die Frage": "питання",
    "die Frau, -en": "жінка",
    "die Geschwister": "брати і сестри",
    "die Großmutter": "бабуся",
    "die Gurke": "огірок",
    "die Hand": "рука",
    "die Idee, -n": "ідея",
    "die Kirsche": "черешня, вишня",
    "die Liebe": "любов, кохання",
    "die Mutter": "мама",
    "die Muttersprache": "рідна мова",
    "die Mütze": "капелюх, шапка",
    "die Nachricht": "повідомлення, новина",
    "die Nase": "ніс",
    "die Nichte": "племінниця",
    "die Oma": "бабуся (скорочено)",
    "die Packung": "пакет, упаковка",
    "die Prüfung": "тест, перевірка, екзамен",
    "die Sahne": "вершки",
    "die Schuhe": "черевик, туфля, взуття",
    "die Schwester": "сестра",
    "die Seite, -n": "сторона, сторінка",
    "die Sonne": "сонце",
    "die Sprache": "мова",
    "die Stadt": "місто",
    "die Stunde, -n": "година",
    "die Suppe, -n": "суп",
    "die Tafel": "дошка (в т.ч. шкільна), плитка, стенд, панель",
    "die Tasse, -n": "чашка",
    "die Tochter": "донька",
    "die Tomate": "помідор",
    "die Weintraube": "виноград",
    "die Witwe": "вдова",
    "die Wohnung": "квартира, житло",
    "die Zahl": "число, кількість, цифра, величина",
    "die Zeit": "час",
    "die Zitrone": "лимон",
    "diese": "цей / ця / ці",
    "dir und dir ?": "тобі, тебе а тебе/тобі ?",
    "doch": "все ж, хоча",
    "dort": "там, туди",
    "drehen": "крутити, повертати, закручувати",
    "durch": "через, скрізь",
    "ehrlich": "чесний, порядний",
    "ein bisschen": "трохи",
    "ein Zug": "поїзд",
    "Eine Milliarde Vier Milliarden": "мільярд 4 мільярди",
    "Eine Million Zwei Millionen": "мільйон 2 мільйони",
    "einen": "об'єднувати",
    "einkaufen": "робити покупки, купувати, покупки",
    "einmal": "якось, один раз, перш за все",
    "Enkelkinder": "онуки",
    "er / es / sie": "він / воно / вона",
    "ergänzen": "доповнювати, додавати",
    "erinnern": "пам'ятати, нагадувати",
    "erste (ерсте)": "перший",
    "etwa": "около, приблизно",
    "etwas wie": "щось на кшталт",
    "fahren": "їхати",
    "falsch": "неправильний, помилковий, фальшивий, неправильно",
    "fest": "міцний, твердий",
    "fotographieren": "фотографувати",
    "frei": "вільний, незалежний, безкоштовний",
    "freut mich": "дуже приємно (ENG: nice to meet you)",
    "froh": "радий, радісний",
    "funktionieren": "працювати, функціонувати",
    "geben": "давати",
    "Geburt": "народження",
    "Geburtsdatum": "дата народження",
    "Geburtsort": "місце народження",
    "gegen": "проти, приблизно, всупереч",
    "gehen": "йти, ходити",
    "Gemüse": "овочі",
    "genau": "точний, точно, правильний",
    "Gepäck": "багаж",
    "geschieden": "розлучений/а",
    "gestern": "вчора",
    "gesundheit": "будь здоровий",
    "glauben": "вірити, вважати",
    "Glückwunsch": "привітання",
    "Großeltern": "бабуся і дідусь",
    "Handynummer": "номер мобільного телефону",
    "hätte gern": "хотів би",
    "Ich hätte gern Pfannkuchen": "я би хотів млинців",
    "Ich hätte gern zu sagen": "я би хотів сказати",
    "Hausaufgabe": "домашнє завдання",
    "heißen": "називатися",
    "Ich heiße ...": "мене звуть ...",
    "Helfen": "допомагати, допомога",
    "Herkunft": "походження, джерело",
    "hören": "чути, слухати",
    "Hunger": "голод",
    "Ich habe eine Schwester": "у мене є сестра",
    "Ich habe Hunger": "я голодний",
    "Ich weiß": "Я знаю",
    "immer noch": "все ще, досі",
    "immer": "завжди, постійно",
    "ja, stimmt": "так, вірно",
    "jetzt": "зараз, тепер",
    "kaputt": "розбитий, поламаний",
    "kaufen": "купувати",
    "kein": "немає, жоден, ніякий",
    "klar": "чіткий, прозорий, зрозумілий, ясно, зрозуміло",
    "kochen": "готувати їжу",
    "Komma": "кома",
    "können": "могти, вміти",
    "kosten": "коштувати, пробувати, пробувати на смак, витрати",
    "kreuzen": "схрещувати, позначати, хрест, пересікати",
    "kurz": "короткий, коротко, стисло",
    "lachen": "сміятися",
    "langsam": "повільний, повільно",
    "leben": "жити, існувати",
    "lecker": "смачний, апетитний",
    "ledig": "неодружений, незаміжня",
    "leid": "жаль, печаль",
    "Lesen": "читати",
    "Lieben": "любити",
    "liegen": "лежати, знаходитись, класти",
    "männlich / weiblich": "чоловічий / жіночий",
    "markieren": "позначати, клеймити",
    "Mehl": "борошно",
    "mehr": "більше, ще",
    "mir": "мені, собі",
    "möchten": "хотіти",
    "Ich möchte / du möchtest": "я хотів би / ти хотів би",
    "möglich": "можливий, можливо",
    "muss": "повинен",
    "müssen": "мусити, бути змушеним",
    "nach": "після",
    "Nachname / Familienname": "прізвище",
    "nachsprechen": "говорити за кимось",
    "natürlich": "натуральний, природній, звичайний, звичайно",
    "nehmen": "брати",
    "neu / neue": "новий / нові",
    "noch": "ще, досі",
    "oben": "зверху, нагорі, вище",
    "Obst": "фрукти",
    "ordnen": "приводити в порядок, систематизовувати",
    "Pfeffer": "перець",
    "Pfund": "фунт, фунт стерлінгів",
    "Prozent": "відсоток",
    "Punkt": "крапка, пункт, стаття, очко, момент",
    "Rabatt": "знижка",
    "Reisen": "подорожувати",
    "richtig": "правильний, правильно",
    "sagen": "говорити, казати",
    "Satz": "речення",
    "schnell": "швидкий, швидко",
    "schwer": "важкий, складний, важко",
    "schwierig": "важкий, складний, важко",
    "sehen": "бачити, дивитися",
    "sich": "сам, себе, собі",
    "Sozialleistungen": "соціальні льготи, виплати",
    "spülen": "мити, полоскати",
    "stehen": "стояти, знаходитися",
    "stimmen": "відповідати дійсності",
    "Stornierung": "відміна",
    "tanzen": "танцювати",
    "toll": "великий, шалений",
    "tut mir leid": "мені шкода",
    "tut": "робити, вчиняти",
    "über": "понад, над, через",
    "sprechen über dich": " говорити про тебе",
    "überprüfen": "контролювати, перевіряти",
    "die Übung": "вправа, тренування, практика",
    "unser": "наші, наш",
    "unten": "нижче, знизу",
    "unter": "під, серед, менше",
    "Unterstrich": "нижнє підкреслення",
    "Verb": "дієслово",
    "verbinden": "з'єднувати, зв'язувати, зкріпляти",
    "verdammen": "проклинати, осуджувати",
    "vergleichen": "порівнювати",
    "verheirated": "одружений / заміжня",
    "verkaufen": "продавати, зраджувати",
    "versuchen": "пробувати, намагатися",
    "verweilen": "перебувати, затримуватись",
    "Verzögerung": "затримка",
    "viel": "багато",
    "vorlesen": "читати вголос",
    "Vorname": "ім'я",
    "vorstelen": "представляти",
    "ich möchte Dennis vorstelen": "я би хотів представити Деніса",
    "ich möchte mich vorstelen": "я би хотів представитись",
    "Vorstellung": "вистава, продуктивність, представлення",
    "warten": "чекати, очікувати",
    "was sprechen Sie ?": "що ви говорите ?",
    "waschen": "мити, прати",
    "wechseln": "міняти, розмінювати",
    "Weihnachten": "Різдво",
    "weil / denn": "тому що",
    "weit": "широкий, далеко",
    "weiter": "далі",
    "welche ?": "котрий ?",
    "welche Sprache sprechen Sie ?": "якою мовою ви говорите ?",
    "werden": "ставати (become)",
    "wichtig": "важливий, важливо",
    "wie alt bist du ?": "скільки тобі років ?",
    "wie geht's?": "як справи?",
    "wie viel kosten das ?": "скільки це коштує ?",
    "wieviel ?": "скільки ?",
    "wo sind Sie geboren ?": "Де Ви народилися ?",
    "Wochenende": "вихідні",
    "woher ?": "звідки ?",
    "worüber ?": "про що ?",
    "Zeichen": "знак",
    "Fragezeichen": "знак питання",
    "Ausrufezeichen": "знак оклику",
    "zeigen": "показувати, вказувати",
    "Zellular": "сотовий зв'язок",
    "zu": "до (ENG: to), в, на, занадто",
    "zur Zeit": "на даний момент",
    "zusammen": "разом, спільно",
    "zwischen": "між"
}
